export const ENTITY_DATA_QUERY_KEY = "ENTITY_DATA_QUERY_KEY";
export const TEST_RUN_DATA_QUERY_KEY = "TEST_RUN_DATA_QUERY_KEY";
export const EMITTER_SITE_DATA_QUERY_KEY = "EMITTER_SITE_DATA_QUERY_KEY";
export const BOUNDARY_DATA_QUERY_KEY = "BOUNDARY_DATA_QUERY_KEY";
export const GOLD_DATA_QUERY_KEY = "GOLD_DATA_QUERY_KEY";
export const EVENT_QUERY_KEY = "EVENT_QUERY_KEY";
